spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: name
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true